### ISSUE TITLE
No statistics written today

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#224]
Hi,

I am running 
ISeeDEDPpl-Questor-6fef21c
and the Settings.xml from 
ISeeDEDPpl-Questor-c7d315d

I seem to have lost all statistics for today (22nd. Logs were written for the 21st just fine.).  Logging is turned on.

  
  
  <consoleLogDaysOfLogsToKeep>30</consoleLogDaysOfLogsToKeep>
  
  <SessionsLog>true</SessionsLog>
  
  <DroneStatsLog>true</DroneStatsLog>
  
  <WreckLootStatistics>false</WreckLootStatistics>
  
  <MissionStats1Log>true</MissionStats1Log>
  
  <MissionStats2Log>true</MissionStats2Log>
  
  <MissionStats3Log>true</MissionStats3Log>
  
  <PocketStatistics>true</PocketStatistics>
  
  <PocketObjectStatisticsLog>true</PocketObjectStatisticsLog>

**Comment by ISeeDEDPpl** [comment]
try again after the last few commits. there were some problems with retrieving the mission list that were resolved there. The statistics routine attempts to pull the list of missions as part of writing the mission statistics and I think it was failing in certain cases. 

https://github.com/ISeeDEDPpl/Questor/commit/4b41e42197cc4df14d9cdd38ea7fafd6bfbfc18e
or newer
https://github.com/ISeeDEDPpl/Questor

**Comment by I3Questor** [comment]
I am now using the current version of Questor (ISeeDEDPpl-Questor-0ea9a5d)

Mission statistics logs are still not being recorded.
