### ISSUE TITLE
Eve freeze when using questor with auto login

### ISSUE THREAD

**Issue by EchuI** [ISeeDEDPpl/Questor#359]
Try with/without stealth, freezes mainly in the character selection screen, sometimes before it, sometimes after. CPU load is 100%, the window eve does not respond to that. Tried to wait about 10 minutes, but nothing has changed.

**Comment by ISeeDEDPpl** [comment]
test bleedingedge please.

**Comment by EchuI** [comment]
still freeze

**Comment by Status12** [comment]
It doesn't freeze with older DirectEVE dll, but it freezes at character selection with the new support version.

**Comment by Chryst** [comment]
Yes with the new DE all getting freeze :( I can confirm that but is the DE not ise.

**Comment by ISeeDEDPpl** [comment]
should be fixed in bleedingedge now. Once its been tested by a few ppl and confirmed working Ill merge it into experimental.

**Comment by kn0xv1lle** [comment]
Still getting this error. Eve freeze at character selection. Using newest Bleedingedge.
Also eve freeze now when login manuel and starting questor manuell. :/

**Comment by ISeeDEDPpl** [comment]
ferox is looking into this, it _seems_ to be a DE issue at this point.

**Comment by Chryst** [comment]
Yeah is a de issue in log in, with bleeding hedge there is the same problem, already tested it in last verison :(

**Comment by drokk99** [comment]
Experimental loads fine for me, Bleeding edge does not, both using the latest de, I log in and start questor manually, and with bleeding edge everything seems to freeze right after loading the settings xml.

**Comment by kn0xv1lle** [comment]
It would crash with experimental too if youre were using auto login...

**Comment by ISeeDEDPpl** [comment]
with the latest DE stealthing is disabled, you should use isxstealth now.
