### ISSUE TITLE
Still attacking targets which are not loced

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#368]
Well this bug is still there. Tries to shoot a target which is not locked. After sometime he seems to attack a locked target. But for a long time he tries to attack a target which is not locked.
Log is

[Combat] Targeting high value target [Striker Alvatis][ID: [truncatedID]48761][14k away] highValueTargets.Count [3]
[CombatMissionCtrl.ClearPocket] Adding [Striker Alvatis] Speed [0,2k/s] Distance [13,75862] [ID: [truncatedID]48761] as
WeaponPriorityTarget [PriorityKillTarget]
[Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]48761][14k away]
[Combat] Targeting high value target [Defeater Alvatis][ID: [truncatedID]48759][17k away] highValueTargets.Count [4]
[Combat] Activating painter [2] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[Combat] Activating weapon  [1] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[Combat] Activating weapon  [2] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[Combat] Activating weapon  [3] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[Combat] Activating painter [2] on [Striker Alvatis][ID: [truncatedID]48761][13k away]
[CombatMissionCtrl.ClearPocket] Adding [Predator Alvior] Speed [0,25k/s] Distance [17,25956] [ID: [truncatedID]49226] as
WeaponPriorityTarget [PriorityKillTarget]
[Combat] Targeting high value target [Alvus Ruler][ID: [truncatedID]49225][18k away] highValueTargets.Count [4]
[Combat] Activating painter [1] on [Defeater Alvatis][ID: [truncatedID]47935][33k away]
[Combat] Activating weapon  [1] on [Defeater Alvatis][ID: [truncatedID]47935][33k away]
[Combat] Activating weapon  [2] on [Defeater Alvatis][ID: [truncatedID]47935][33k away]
[Combat] Activating painter [1] on [Predator Alvior][ID: [truncatedID]49226][21k away]
[Combat] Activating painter [2] on [Predator Alvior][ID: [truncatedID]49226][22k away]
[Combat] Activating painter [1] on [Predator Alvior][ID: [truncatedID]49226][23k away]
[Combat] Activating painter [2] on [Predator Alvior][ID: [truncatedID]49226][24k away]
[CombatMissionCtrl.ClearPocket] Adding [Dismantler Alvior] Speed [0,25k/s] Distance [23,83235] [ID: [truncatedID]49222]
aryWeaponPriorityTarget [PriorityKillTarget]
[Combat] Activating painter [1] on [Dismantler Alvior][ID: [truncatedID]49222][24k away]
[Combat] Activating painter [1] on [Dismantler Alvior][ID: [truncatedID]49222][25k away]
[Defense] Shields: [75%] Cap: [72%] Shield Booster: [1] activated
[Combat] Activating painter [2] on [Dismantler Alvior][ID: [truncatedID]49222][26k away]
[Combat] Activating painter [1] on [Dismantler Alvior][ID: [truncatedID]49222][27k away]
[CombatMissionCtrl.ClearPocket] Out of range. ignoring orbit around structure.
[CombatMissionCtrl.ClearPocket] Initiating Orbit [Dismantler Alvior][at 15k][ID: [truncatedID]49222]
[Combat] Activating painter [2] on [Dismantler Alvior][ID: [truncatedID]49222][27k away]
[Combat] Activating painter [1] on [Dismantler Alvior][ID: [truncatedID]49222][28k away]
[Combat] Activating painter [2] on [Dismantler Alvior][ID: [truncatedID]49222][27k away]
[Combat] Activating painter [1] on [Dismantler Alvior][ID: [truncatedID]49222][25k away]
[Defense] Shields: [86%] Cap: [65%] Shield Booster: [1] deactivated [2] sec reactivation delay
[Combat] Activating painter [2] on [Dismantler Alvior][ID: [truncatedID]49222][24k away]
[Combat] Activating painter [1] on [Predator Alvior][ID: [truncatedID]49226][21k away]
[Combat] Activating painter [1] on [Predator Alvior][ID: [truncatedID]49226][20k away]
[Combat] Activating painter [2] on [Predator Alvior][ID: [truncatedID]49226][18k away]
[Combat] Activating painter [2] on [Predator Alvior][ID: [truncatedID]49226][17k away]
[Combat] Activating painter [1] on [Predator Alvior][ID: [truncatedID]49226][15k away]

**Comment by Pluckyduck** [comment]
what DE version are you running?

**Comment by ISeeDEDPpl** [comment]
When was that compiled? what github rev?

**Comment by ISeeDEDPpl** [comment]
Can you reproduce that log with
`<debugGetBestTarget>true</debugGetBestTarget>`
in your characters settings xml please.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge. We not trust that combat.cs is choosing the right targets for us to shoot. GetBestTarget never targets things anyway so we should have always limited ourselves to active targets. This is now fixed. 
https://github.com/ISeeDEDPpl/Questor/commit/086ba04bc9a63b31cd5205303a375145f63f7198

**Comment by kn0xv1lle** [comment]
Thanks isee will test it. Used latest direct eve and latest version of your questor version. When it still happen i will make a debug log.

**Comment by kn0xv1lle** [comment]
Still getting this error. Have a debug log for you. Using newest experimental and newest direct eve with isxstealth. After questor gets out of range of the target he unlock it and lock a new one. Then its working like it should. But its a very long time where he does nothing. Problem is also webber and disrupter which are not permanently webbing and disrupting. If 5 targets are already locked he tries to target them.

11:24:23 [Combat Debug: GetBestTarget] CurrentTarget [Corpus Prophet][19,81k][[truncatedID]75302]
11:24:25 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:25 [Combat Debug: GetBestTarget] CurrentTarget [Corpus Prophet][20,43k][[truncatedID]75302]
11:24:28 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:28 [Combat Debug: GetBestTarget] CurrentTarget [Corpus Prophet][20,63k][[truncatedID]75302]
11:24:30 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:30 [Combat Debug: GetBestTarget] CurrentTarget [Corpus Prophet][21,85k][[truncatedID]75302]
11:24:33 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:33 [Combat Debug: GetBestTarget] CurrentTarget [Corpus Prophet][21,85k][[truncatedID]75302]
11:24:33 [Combat] Changing [2] with [Scourge Rage Heavy Assault Missile][33][TypeID: 2679] so we can hit [Corpus Prophet][22k]
11:24:34 [Combat] Targeting high value target [Corpum Arch Sage][ID: [truncatedID]75332][25k away] highValueTargets.Count [4]
11:24:35 [Combat Debug: GetBestTarget:] highValueTarget is [Corpum Revenant][21,72k][[truncatedID]75307]
11:24:35 [Combat] Activating painter [1] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:35 [Combat] Activating weapon [1] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:35 [Combat] Activating weapon [2] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:38 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:38 [Combat Debug: GetBestTarget] CurrentTarget [Corpum Revenant][22,01k][[truncatedID]75307]
11:24:38 [Combat] Activating painter [2] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:38 [Combat] Activating weapon [2] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:38 [Combat] Activating weapon [3] on [Corpum Revenant][ID: [truncatedID]75307][22k away]
11:24:40 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:40 [Combat Debug: GetBestTarget] CurrentTarget [Corpum Revenant][23,32k][[truncatedID]75307]
11:24:42 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:42 [Combat Debug: GetBestTarget] CurrentTarget [Corpum Revenant][23,94k][[truncatedID]75307]
11:24:44 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:44 [Combat Debug: GetBestTarget] CurrentTarget [Corpum Revenant][24,69k][[truncatedID]75307]
11:24:44 [Combat] Activating weapon [2] on [Corpum Revenant][ID: [truncatedID]75307][25k away]
11:24:46 [Combat Debug: GetBestTarget] if (currentTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(currentTarget.Name.Trim()) && PrimaryWeaponPriorityTargets.Any(pt => pt.Id == currentTarget.Id))
11:24:46 [Combat Debug: GetBestTarget] CurrentTarget [Corpum Revenant][25,58k][[truncatedID]75307]
11:24:46 [CombatMissionCtrl.ClearPocket] Adding [Corpum Arch Sage] Speed [0,21k/s] Distance [26,66292] [ID: [truncatedID]75332] as a PrimaryWeaponPriorityTarget [PriorityKillTarget]
11:24:47 [Combat] Targeting high value target [Corpus Archon][ID: [truncatedID]75330][33k away] highValueTargets.Count [4]
11:24:47 [CombatMissionCtrl.ClearPocket] Adding [Corpii Raider] Speed [0,43k/s] Distance [26,85202] [ID: [truncatedID]75328] as a PrimaryWeaponPriorityTarget [PriorityKillTarget]
11:24:49 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:24:49 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,85k][[truncatedID]75328]
11:24:51 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:24:51 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,77k][[truncatedID]75328]
11:24:53 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:24:53 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,73k][[truncatedID]75328]
11:24:56 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:24:56 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,72k][[truncatedID]75328]
11:24:58 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:24:58 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,77k][[truncatedID]75328]
11:24:58 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][27k away]
11:25:00 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:00 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,83k][[truncatedID]75328]
11:25:00 [Combat] Activating painter [2] on [Corpii Raider][ID: [truncatedID]75328][27k away]
11:25:02 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:02 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,91k][[truncatedID]75328]
11:25:04 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:04 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][27,02k][[truncatedID]75328]
11:25:04 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][27k away]
11:25:06 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:06 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][27,14k][[truncatedID]75328]
11:25:06 [Combat] Activating painter [2] on [Corpii Raider][ID: [truncatedID]75328][27k away]
11:25:09 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:09 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][27,37k][[truncatedID]75328]
11:25:10 [CombatMissionCtrl.ClearPocket] Out of range. ignoring orbit around structure.
11:25:10 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Corpii Raider][at 15k][ID: [truncatedID]75328]
11:25:11 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:11 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][27,53k][[truncatedID]75328]
11:25:11 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][28k away]
11:25:13 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:13 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][27,52k][[truncatedID]75328]
11:25:13 [Combat] Activating painter [2] on [Corpii Raider][ID: [truncatedID]75328][28k away]
11:25:15 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:15 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][26,55k][[truncatedID]75328]
11:25:18 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:18 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][25,48k][[truncatedID]75328]
11:25:18 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][25k away]
11:25:20 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:20 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][23,83k][[truncatedID]75328]
11:25:20 [Combat] Activating painter [2] on [Corpii Raider][ID: [truncatedID]75328][24k away]
11:25:22 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:22 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][21,86k][[truncatedID]75328]
11:25:24 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:24 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][20,62k][[truncatedID]75328]
11:25:24 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][21k away]
11:25:26 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:26 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][19,19k][[truncatedID]75328]
11:25:26 [Combat] Activating painter [2] on [Corpii Raider][ID: [truncatedID]75328][19k away]
11:25:28 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:28 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][18,57k][[truncatedID]75328]
11:25:30 [Combat Debug: GetBestTarget:] if (primaryWeaponPriorityTarget != null && callingroutine == Combat && !Cache.Instance.IgnoreTargets.Contains(primaryWeaponPriorityTarget.Name.Trim()))
11:25:30 [Combat Debug: GetBestTarget:] primaryWeaponPriorityTarget is [Corpii Raider][16,08k][[truncatedID]75328]
11:25:30 [Combat] Activating painter [1] on [Corpii Raider][ID: [truncatedID]75328][16k away]

**Comment by ISeeDEDPpl** [comment]
Ive made some changes in bleedingedge, hopefully for the better.
please regenerate the above log.

**Comment by ISeeDEDPpl** [comment]
this will need more attention from me tonight however as we evidently do not free up targeting slots correctly in all cases...

**Comment by bugc** [comment]
so, any progress here? I'm waiting too for solution. As mentioned before it could cost a ship or two.

**Comment by ISeeDEDPpl** [comment]
I think this is fixed tbh. but Ill look into it again to be sure. feel free to help =/

**Comment by kn0xv1lle** [comment]
This should be fixed. Never saw it again on my chars with newest build and newest setting xml.
